// Database types - Generated from Supabase schema
// These types should be regenerated when schema changes

export type UserRole = 'admin' | 'customer' | 'store' | 'guest';
export type AuthProvider = 'email' | 'phone' | 'google' | 'facebook' | 'apple';
export type ProductCategory = string;
export type AvailabilityStatus = 'in_stock' | 'out_of_stock' | 'limited_stock' | 'pre_order';
export type TransactionStatus = 'pending' | 'completed' | 'failed' | 'refunded';
export type NotificationType = 'price_drop' | 'back_in_stock' | 'deal_alert' | 'deal' | 'system' | 'account';
export type StoreStatus = 'active' | 'pending' | 'suspended' | 'inactive';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          full_name: string | null;
          role: UserRole;
          auth_provider: AuthProvider;
          auth_provider_id: string | null;
          avatar_url: string | null;
          email_verified: boolean;
          phone_verified: boolean;
          preferred_language: string;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          full_name?: string | null;
          role?: UserRole;
          auth_provider?: AuthProvider;
          auth_provider_id?: string | null;
          avatar_url?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          preferred_language?: string;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          full_name?: string | null;
          role?: UserRole;
          auth_provider?: AuthProvider;
          auth_provider_id?: string | null;
          avatar_url?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          preferred_language?: string;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stores: {
        Row: {
          id: string;
          name_ar: string;
          name_en: string;
          slug: string;
          logo_url: string | null;
          website_url: string;
          description_ar: string | null;
          description_en: string | null;
          status: StoreStatus;
          contact_email: string | null;
          contact_phone: string | null;
          api_endpoint: string | null;
          requires_scraping: boolean;
          last_sync_at: string | null;
          delivery_info_ar: string | null;
          delivery_info_en: string | null;
          return_policy_ar: string | null;
          return_policy_en: string | null;
          warranty_info_ar: string | null;
          warranty_info_en: string | null;
          average_rating: number;
          total_reviews: number;
          total_products: number;
          commission_rate: number;
          is_premium: boolean;
          is_featured: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name_ar: string;
          name_en: string;
          slug: string;
          logo_url?: string | null;
          website_url: string;
          description_ar?: string | null;
          description_en?: string | null;
          status?: StoreStatus;
          contact_email?: string | null;
          contact_phone?: string | null;
          api_endpoint?: string | null;
          requires_scraping?: boolean;
          last_sync_at?: string | null;
          delivery_info_ar?: string | null;
          delivery_info_en?: string | null;
          return_policy_ar?: string | null;
          return_policy_en?: string | null;
          warranty_info_ar?: string | null;
          warranty_info_en?: string | null;
          average_rating?: number;
          total_reviews?: number;
          total_products?: number;
          commission_rate?: number;
          is_premium?: boolean;
          is_featured?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name_ar?: string;
          name_en?: string;
          slug?: string;
          logo_url?: string | null;
          website_url?: string;
          description_ar?: string | null;
          description_en?: string | null;
          status?: StoreStatus;
          contact_email?: string | null;
          contact_phone?: string | null;
          api_endpoint?: string | null;
          requires_scraping?: boolean;
          last_sync_at?: string | null;
          delivery_info_ar?: string | null;
          delivery_info_en?: string | null;
          return_policy_ar?: string | null;
          return_policy_en?: string | null;
          warranty_info_ar?: string | null;
          warranty_info_en?: string | null;
          average_rating?: number;
          total_reviews?: number;
          total_products?: number;
          commission_rate?: number;
          is_premium?: boolean;
          is_featured?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          name_ar: string;
          name_en: string;
          slug: string;
          category: ProductCategory;
          brand: string;
          model: string;
          sku: string | null;
          description_ar: string | null;
          description_en: string | null;
          image_urls: string[] | null;
          video_url: string | null;
          specifications: Record<string, unknown> | null;
          view_count: number;
          save_count: number;
          comparison_count: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_ar: string;
          name_en: string;
          slug: string;
          category: ProductCategory;
          brand: string;
          model: string;
          sku?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          image_urls?: string[] | null;
          video_url?: string | null;
          specifications?: Record<string, unknown> | null;
          view_count?: number;
          save_count?: number;
          comparison_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name_ar?: string;
          name_en?: string;
          slug?: string;
          category?: ProductCategory;
          brand?: string;
          model?: string;
          sku?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          image_urls?: string[] | null;
          video_url?: string | null;
          specifications?: Record<string, unknown> | null;
          view_count?: number;
          save_count?: number;
          comparison_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_stores: {
        Row: {
          id: string;
          product_id: string;
          store_id: string;
          current_price: number;
          original_price: number | null;
          currency: string;
          availability: AvailabilityStatus;
          stock_quantity: number | null;
          product_url: string;
          affiliate_url: string | null;
          delivery_time_days: number | null;
          delivery_cost: number;
          is_free_delivery: boolean;
          is_deal: boolean;
          deal_expires_at: string | null;
          coupon_code: string | null;
          last_checked_at: string;
          last_price_change_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          store_id: string;
          current_price: number;
          original_price?: number | null;
          currency?: string;
          availability?: AvailabilityStatus;
          stock_quantity?: number | null;
          product_url: string;
          affiliate_url?: string | null;
          delivery_time_days?: number | null;
          delivery_cost?: number;
          is_free_delivery?: boolean;
          is_deal?: boolean;
          deal_expires_at?: string | null;
          coupon_code?: string | null;
          last_checked_at?: string;
          last_price_change_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          store_id?: string;
          current_price?: number;
          original_price?: number | null;
          currency?: string;
          availability?: AvailabilityStatus;
          stock_quantity?: number | null;
          product_url?: string;
          affiliate_url?: string | null;
          delivery_time_days?: number | null;
          delivery_cost?: number;
          is_free_delivery?: boolean;
          is_deal?: boolean;
          deal_expires_at?: string | null;
          coupon_code?: string | null;
          last_checked_at?: string;
          last_price_change_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      price_history: {
        Row: {
          id: string;
          product_store_id: string;
          price: number;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          product_store_id: string;
          price: number;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          product_store_id?: string;
          price?: number;
          recorded_at?: string;
        };
        Relationships: [];
      };
      user_wishlists: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      search_history: {
        Row: {
          id: string;
          user_id: string | null;
          search_query: string;
          category: ProductCategory | null;
          filters: Record<string, unknown> | null;
          results_count: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          search_query: string;
          category?: ProductCategory | null;
          filters?: Record<string, unknown> | null;
          results_count?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          search_query?: string;
          category?: ProductCategory | null;
          filters?: Record<string, unknown> | null;
          results_count?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      transactions: {
        Row: {
          id: string;
          user_id: string | null;
          product_store_id: string;
          amount: number;
          commission_amount: number | null;
          commission_rate: number | null;
          status: TransactionStatus;
          click_id: string | null;
          clicked_at: string | null;
          converted_at: string | null;
          user_agent: string | null;
          ip_address: string | null;
          referrer: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          product_store_id: string;
          amount?: number;
          commission_amount?: number | null;
          commission_rate?: number | null;
          status?: TransactionStatus;
          click_id?: string | null;
          clicked_at?: string | null;
          converted_at?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          referrer?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          product_store_id?: string;
          amount?: number;
          commission_amount?: number | null;
          commission_rate?: number | null;
          status?: TransactionStatus;
          click_id?: string | null;
          clicked_at?: string | null;
          converted_at?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          referrer?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      store_reviews: {
        Row: {
          id: string;
          store_id: string;
          user_id: string;
          rating: number;
          review_text: string | null;
          delivery_rating: number | null;
          product_quality_rating: number | null;
          customer_service_rating: number | null;
          is_verified_purchase: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          user_id: string;
          rating: number;
          review_text?: string | null;
          delivery_rating?: number | null;
          product_quality_rating?: number | null;
          customer_service_rating?: number | null;
          is_verified_purchase?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          user_id?: string;
          rating?: number;
          review_text?: string | null;
          delivery_rating?: number | null;
          product_quality_rating?: number | null;
          customer_service_rating?: number | null;
          is_verified_purchase?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          title_ar: string;
          title_en: string;
          message_ar: string | null;
          message_en: string | null;
          product_id: string | null;
          product_store_id: string | null;
          store_id: string | null;
          link: string | null;
          data: Record<string, unknown> | null;
          is_read: boolean;
          is_sent: boolean;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: NotificationType;
          title_ar: string;
          title_en: string;
          message_ar?: string | null;
          message_en?: string | null;
          product_id?: string | null;
          product_store_id?: string | null;
          store_id?: string | null;
          link?: string | null;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          is_sent?: boolean;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: NotificationType;
          title_ar?: string;
          title_en?: string;
          message_ar?: string | null;
          message_en?: string | null;
          product_id?: string | null;
          product_store_id?: string | null;
          store_id?: string | null;
          link?: string | null;
          data?: Record<string, unknown> | null;
          is_read?: boolean;
          is_sent?: boolean;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      price_alerts: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          target_price: number;
          is_active: boolean;
          notified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          target_price: number;
          is_active?: boolean;
          notified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          target_price?: number;
          is_active?: boolean;
          notified_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          details: Record<string, unknown> | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          details?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          details?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          notification_preferences: Record<string, unknown> | null;
          privacy_preferences: Record<string, unknown> | null;
          app_preferences: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          notification_preferences?: Record<string, unknown> | null;
          privacy_preferences?: Record<string, unknown> | null;
          app_preferences?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          notification_preferences?: Record<string, unknown> | null;
          privacy_preferences?: Record<string, unknown> | null;
          app_preferences?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      auth_provider: AuthProvider;
      product_category: ProductCategory;
      availability_status: AvailabilityStatus;
      transaction_status: TransactionStatus;
      notification_type: NotificationType;
      store_status: StoreStatus;
    };
    CompositeTypes: Record<string, never>;
  };
}
