// scripts/tps-analysis/rehearsal/gen-schema.ts
// Builds the replica DDL from the PRODUCTION CATALOG (read-only) and writes
//   schema.generated.sql   (pre-data / post-data sections, see markers)
//   schema.meta.json       (per-table column + PK metadata used by the loader and the parity report)
// Run directly:  npx tsx scripts/tps-analysis/rehearsal/gen-schema.ts
import * as fs from "node:fs";
import * as path from "node:path";
import { DIR, prodClient, type ProdClient } from "./lib";

/** Dependency order (parents first). */
export const TABLES = [
  "stores",
  "canonical_products",
  "normalized_product_observations",
  "product_matches",
  "price_history",
  "raw_observations",
  "tps_identity_staging",
  "tps_current_offers",
  "tps_progress_cursors",
  "tps_price_implausibility_signals",
  "tps_offer_delist_signals",
  "tps_product_projection",
  "samsung_official_url_baseline", // engine reads it (verified-Samsung-model registry)
] as const;
export const FUNCTIONS = ["write_ac_batch"] as const;

export interface ColMeta { name: string; type: string; notNull: boolean; identity: "" | "a" | "d"; generated: string; default: string | null; collation: string | null }
export interface TableMeta { name: string; cols: ColMeta[]; pk: string[]; pkTypes: string[]; prodRowEstimate: number }
export interface Omission { kind: string; object: string; detail: string }
export interface SchemaMeta { generatedAt: string; prodVersion: string; tables: TableMeta[]; constraints: { table: string; name: string; type: string; def: string }[]; fks: { table: string; name: string; def: string; kept: boolean; reason?: string }[]; indexes: { table: string; name: string; def: string }[]; functions: { name: string; sig: string }[]; sequences: string[]; omissions: Omission[] }

const q = (id: string) => `"${id.replace(/"/g, '""')}"`;
const inList = TABLES.map((t) => `'${t}'`).join(",");

export async function generateSchema(prod: ProdClient): Promise<{ sql: string; meta: SchemaMeta }> {
  await prod.query("begin read only");
  try {
    const version = (await prod.query("select version() v"))[0].v as string;
    const omissions: Omission[] = [];
    const sequences = new Set<string>();
    const tables: TableMeta[] = [];

    const cols = await prod.query(`
      select c.relname t, a.attnum, a.attname n, format_type(a.atttypid, a.atttypmod) ty, a.attnotnull nn, a.attidentity idn, a.attgenerated gen,
             pg_get_expr(d.adbin, d.adrelid) def,
             case when a.attcollation <> t.typcollation and a.attcollation <> 0 then (select collname from pg_collation where oid = a.attcollation) end coll
        from pg_attribute a join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace
        join pg_type t on t.oid = a.atttypid
        left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
       where n.nspname = 'public' and c.relname in (${inList}) and a.attnum > 0 and not a.attisdropped
       order by c.relname, a.attnum`);
    const est = await prod.query(`select relname, reltuples::bigint est from pg_class where relnamespace = 'public'::regnamespace and relname in (${inList})`);
    const pkq = await prod.query(`
      select c.relname t, array_agg(a.attname::text order by k.ord) cols, array_agg(format_type(a.atttypid, a.atttypmod) order by k.ord) types
        from pg_constraint con join pg_class c on c.oid = con.conrelid
        cross join lateral unnest(con.conkey) with ordinality k(attnum, ord)
        join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum
       where con.contype = 'p' and c.relnamespace = 'public'::regnamespace and c.relname in (${inList}) group by c.relname`);

    const ddl: string[] = [];
    const post: string[] = [];
    ddl.push("-- ===== PRE-DATA: tables, primary/unique/check constraints =====");
    for (const t of TABLES) {
      const tc = cols.filter((r: any) => r.t === t);
      if (!tc.length) throw new Error(`table ${t} not found in production catalog`);
      const colMeta: ColMeta[] = tc.map((r: any) => ({ name: r.n, type: r.ty, notNull: r.nn, identity: r.idn, generated: r.gen, default: r.def, collation: r.coll }));
      const lines = colMeta.map((c) => {
        let s = `  ${q(c.name)} ${c.type}`;
        if (c.collation) { s += ` COLLATE ${q(c.collation)}`; omissions.push({ kind: "collation", object: `${t}.${c.name}`, detail: `non-default collation ${c.collation} kept` }); }
        if (c.identity === "a") s += " GENERATED ALWAYS AS IDENTITY";
        else if (c.identity === "d") s += " GENERATED BY DEFAULT AS IDENTITY";
        else if (c.generated === "s") s += ` GENERATED ALWAYS AS (${c.default}) STORED`;
        else if (c.default != null) {
          s += ` DEFAULT ${c.default}`;
          const m = /nextval\('([^']+)'::regclass\)/.exec(c.default);
          if (m) sequences.add(`${m[1].replace(/^public\./, "")}|${t}.${c.name}`);
        }
        if (c.notNull && c.identity === "") s += " NOT NULL";
        return s;
      });
      ddl.push(`CREATE TABLE public.${q(t)} (\n${lines.join(",\n")}\n);`);
      const pk = pkq.find((r: any) => r.t === t);
      tables.push({ name: t, cols: colMeta, pk: pk?.cols ?? [], pkTypes: pk?.types ?? [], prodRowEstimate: Number(est.find((r: any) => r.relname === t)?.est ?? -1) });
    }
    // sequences must exist before the tables that default to them
    if (sequences.size) {
      const seqSql = [...sequences].map((s) => `CREATE SEQUENCE IF NOT EXISTS public.${q(s.split("|")[0])};`);
      ddl.splice(1, 0, ...seqSql);
      for (const s of sequences) { const [seq, col] = s.split("|"); const [tb, cl] = col.split("."); post.push(`ALTER SEQUENCE public.${q(seq)} OWNED BY public.${q(tb)}.${q(cl)};`); }
    }

    const cons = await prod.query(`
      select c.relname t, con.conname n, con.contype ty, pg_get_constraintdef(con.oid) d, con.confrelid::regclass::text ref
        from pg_constraint con join pg_class c on c.oid = con.conrelid
       where c.relnamespace = 'public'::regnamespace and c.relname in (${inList}) and con.contype in ('p','u','c','f')
       order by c.relname, case con.contype when 'p' then 1 when 'u' then 2 when 'c' then 3 else 4 end, con.conname`);
    const constraints: SchemaMeta["constraints"] = [];
    const fks: SchemaMeta["fks"] = [];
    const fkSql: string[] = [];
    for (const r of cons) {
      if (r.ty === "f") {
        const refTable = String(r.ref).replace(/^public\./, "").replace(/"/g, "");
        const kept = (TABLES as readonly string[]).includes(refTable);
        // FKs to replicated tables are kept, EXCEPT the ones the sampled data cannot satisfy by construction.
        const dropCopy = r.n === "price_history_raw_observation_id_fkey"; // raw sample is 3 days; price_history is full-history for mobile/tv
        const reason = !kept ? `references ${refTable}, not replicated` : dropCopy ? "raw_observations is a 3-day sample; copied price_history rows reference older raw rows (engine writes NULL here)" : undefined;
        const keep = kept && !dropCopy;
        fks.push({ table: r.t, name: r.n, def: r.d, kept: keep, reason });
        if (keep) fkSql.push(`ALTER TABLE public.${q(r.t)} ADD CONSTRAINT ${q(r.n)} ${r.d};`);
        else omissions.push({ kind: "foreign key", object: `${r.t}.${r.n}`, detail: `${r.d} — ${reason}` });
      } else {
        constraints.push({ table: r.t, name: r.n, type: r.ty, def: r.d });
        ddl.push(`ALTER TABLE public.${q(r.t)} ADD CONSTRAINT ${q(r.n)} ${r.d};`);
      }
    }

    // Inbound FKs from tables that are not replicated (documented only)
    const inbound = await prod.query(`
      select c.relname t, con.conname n, pg_get_constraintdef(con.oid) d, con.confrelid::regclass::text ref
        from pg_constraint con join pg_class c on c.oid = con.conrelid
       where con.contype = 'f' and con.confrelid::regclass::text in (${inList}) and c.relname not in (${inList}) and c.relnamespace = 'public'::regnamespace`);
    for (const r of inbound) omissions.push({ kind: "inbound FK / dependent table", object: r.t, detail: `${r.n}: ${r.d} (table not replicated)` });

    // Indexes that are not owned by a constraint
    const idx = await prod.query(`
      select i.tablename t, i.indexname n, i.indexdef d
        from pg_indexes i
       where i.schemaname = 'public' and i.tablename in (${inList})
         and not exists (select 1 from pg_constraint con where con.conindid = (quote_ident(i.schemaname)||'.'||quote_ident(i.indexname))::regclass and con.contype in ('p','u'))
       order by i.tablename, i.indexname`);
    const indexes: SchemaMeta["indexes"] = idx.map((r: any) => ({ table: r.t, name: r.n, def: r.d }));

    // Functions
    const fns = await prod.query(`
      select p.proname n, p.oid::regprocedure::text sig, pg_get_functiondef(p.oid) def
        from pg_proc p where p.pronamespace = 'public'::regnamespace and p.proname = any($1::text[]) order by 1`, [FUNCTIONS as unknown as string[]]);
    for (const f of FUNCTIONS) if (!fns.find((r: any) => r.n === f)) throw new Error(`function ${f} not found in production`);

    // Triggers (documented; the replicated tables currently have none)
    const trg = await prod.query(`select tgrelid::regclass::text t, tgname from pg_trigger where not tgisinternal and tgrelid::regclass::text in (${inList})`);
    for (const r of trg) omissions.push({ kind: "trigger", object: `${r.t}.${r.tgname}`, detail: "not replicated" });

    // Other public functions that read/write the replicated tables (documented omission, not copied)
    const other = await prod.query(`
      select p.oid::regprocedure::text sig from pg_proc p
       where p.pronamespace = 'public'::regnamespace and p.prokind = 'f' and p.proname <> all($1::text[])
         and p.prosrc ~* '(canonical_products|normalized_product_observations|product_matches|price_history|tps_current_offers|tps_identity_staging)'
       order by 1`, [FUNCTIONS as unknown as string[]]);
    for (const r of other) omissions.push({ kind: "function (not copied)", object: r.sig, detail: "references replicated tables but is not on the engine write path (runSweepUnit only calls write_ac_batch)" });

    const out: string[] = [];
    out.push(`-- schema.generated.sql — GENERATED from the production catalog (read-only) by gen-schema.ts`);
    out.push(`-- source: ${version}`);
    out.push(`-- generated: ${new Date().toISOString()}`);
    out.push("-- Do not edit by hand; re-run `npx tsx scripts/tps-analysis/rehearsal/setup.ts` (or gen-schema.ts).");
    out.push("");
    out.push(...ddl);
    out.push("");
    out.push("-- ===== FUNCTIONS =====");
    for (const f of fns) out.push(f.def.trim().replace(/CREATE OR REPLACE FUNCTION/, "CREATE OR REPLACE FUNCTION") + ";", "");
    out.push("-- ===== POST-DATA: sequence ownership, non-constraint indexes, foreign keys, RLS, grants =====");
    out.push(...post);
    for (const i of indexes) out.push(i.def.replace(/^CREATE (UNIQUE )?INDEX /, "CREATE $1INDEX IF NOT EXISTS ") + ";");
    out.push(...fkSql);
    for (const t of TABLES) out.push(`ALTER TABLE public.${q(t)} ENABLE ROW LEVEL SECURITY;`);
    out.push("GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;");
    out.push("GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;");
    out.push("GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;");
    out.push("GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;");
    out.push("");

    const meta: SchemaMeta = {
      generatedAt: new Date().toISOString(), prodVersion: version, tables, constraints, fks, indexes,
      functions: fns.map((r: any) => ({ name: r.n, sig: r.sig })), sequences: [...sequences], omissions,
    };
    return { sql: out.join("\n"), meta };
  } finally {
    await prod.query("rollback");
  }
}

export async function writeSchemaFiles(prod: ProdClient) {
  const { sql, meta } = await generateSchema(prod);
  fs.writeFileSync(path.join(DIR, "schema.generated.sql"), sql);
  fs.writeFileSync(path.join(DIR, "schema.meta.json"), JSON.stringify(meta, null, 2));
  return meta;
}

if (require.main === module) {
  (async () => {
    const prod = await prodClient();
    try { const m = await writeSchemaFiles(prod); console.log(`schema.generated.sql written: ${m.tables.length} tables, ${m.constraints.length} constraints, ${m.fks.filter((f) => f.kept).length}/${m.fks.length} FKs kept, ${m.indexes.length} indexes, ${m.functions.length} functions`); }
    finally { await prod.end(); }
  })().catch((e) => { console.error(e); process.exit(1); });
}
